version: "3.1"

services:

  server:
    container_name: hex-server
    build:
      context: .
      dockerfile: ./Dockerfile.server
    volumes:
      - ./docker/certs:/opt/app/certs
      - ./docker/logs:/opt/app/logs
      - ./dist/server/src:/opt/app/src
    ports:
      - ${SERVER_WS_PORT}:${SERVER_WS_PORT}
    environment:
      SERVER_WS_PORT: ${SERVER_WS_PORT}
      SERVER_WS_CERT_FILE: ${SERVER_WS_CERT_FILE}
      SERVER_WS_KEY_FILE: ${SERVER_WS_KEY_FILE}
      SERVER_CORS_ORIGIN: ${SERVER_CORS_ORIGIN}
    working_dir: /opt/app
    command: forever -o /opt/app/logs/server.out.log -e /opt/app/logs/server.err.log ./src/index.js

  client:
    container_name: hex-client
    image: nginx:alpine
    volumes:
      - ./dist/client:/opt/client/html:ro
      - ./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certs:/opt/client/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
